apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: arthtmlapp
  name: arthtmlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arthtmlapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arthtmlapp
    spec:
      containers:
      - image: arthurferreira2/oracleweb:v2
        name: oracleweb
        resources: {}
status: {}
